import os

LAKEFS_SERVER_ADDRESS = os.getenv('LAKEFS_SERVER_ADDRESS', 'http://localhost:8000')
LAKEFS_ACCESS_KEY_ID = os.getenv('LAKEFS_ACCESS_KEY_ID')
LAKEFS_SECRET_ACCESS_KEY = os.getenv('LAKEFS_SECRET_ACCESS_KEY')
